### ISSUE TITLE
[DATA] Weather data dev_in empty

### ISSUE THREAD

**Issue by cmougan** [yandex-research/shifts#16]
The weather data has the following numbers of rows:
- train.csv = 808952
- dev_in.csv = 1
- dev_out.csv = 50001

Is the dev_in intended to be empty? What I understand from the paper is that it should not

<img width="1064" alt="Screenshot 2021-08-13 at 09 29 41" src="https://user-images.githubusercontent.com/43068386/129373194-c51fd250-fe00-4c36-bd90-ca157a838d2a.png">

**Comment by KaosEngineer** [comment]
This is an issue on your end - I just re-downloaded the data and all files have the correct number of lines. Could you have accidentally overwritten the file?
