### ISSUE TITLE
Some clarity on the number of columns in the weather dataset

### ISSUE THREAD

**Issue by jaberkow** [yandex-research/shifts#17]
Both the paper describing the dataset and the website for the challenge claim there are 111 features in total for the weather dataset.  However, both the train and dev datasets released currently include 129 columns.  Following the tutorial it seems clear that the first 6 columns are metadata or target values, and probably won't be included in the final eval data.  However, that still leaves 123 columns.   Would it be possible to get a list of the columns that will be available in the eval data?

**Comment by KaosEngineer** [comment]
There should be 123 columns - the original figure of 111 was wrong (that was the number of features on a previous iteration of the data)

Here are the column values and descriptions

climate_pressure - climate pressure, mmHg 
climate_temperature - climate temperature, C 
cmc_0_0_0_1000 - temperature at 1000 isobaric level, K
cmc_0_0_0_2 - temperature at 2m, K
cmc_0_0_0_2_grad - difference between temperatures on adjacent horizons at 2m, K
cmc_0_0_0_2_interpolated - temperature at 2m interpolated between horizons, K
cmc_0_0_0_2_next - temperature at 2m for next horizon, K
cmc_0_0_0_500 - temperature at 500 isobaric level, K
cmc_0_0_0_700 - temperature at 700 isobaric level, K
cmc_0_0_0_850 - temperature at 850 isobaric level, K
cmc_0_0_0_925 - temperature at 925 isobaric level, K
cmc_0_0_6_2 - dew point temp at 2m, K
cmc_0_0_7_1000 - dew point depression at 1000 isobaric level, K
cmc_0_0_7_2 - dew point depression at 2m, K
cmc_0_0_7_500 - dew point depression at 500 isobaric level, K
cmc_0_0_7_700 - dew point depression at 700 isobaric level, K
cmc_0_0_7_850 - dew point depression at 850 isobaric level, K
cmc_0_0_7_925 - dew point depression at 925 isobaric level, K
cmc_0_1_0_0 - absolute humidity from 0 to 1
cmc_0_1_11_0 - snow depth, m
cmc_0_1_65_0 - rain accumulated from cmc gentime, mm
cmc_0_1_65_0_grad - rain accumulated from cmc gentime difference between adjacent horizons, mm
cmc_0_1_65_0_next - rain accumulated from cmc gentime for next horizon, mm
cmc_0_1_66_0 - snow accumulated from cmc gentime, mm
cmc_0_1_66_0_grad - snow accumulated from cmc gentime difference between adjacent horizons, mm
cmc_0_1_66_0_next - snow accumulated from cmc gentime for next horizon, mm
cmc_0_1_67_0 - ice rain accumulated from cmc gentime, mm
cmc_0_1_67_0_grad - ice rain accumulated from cmc gentime difference between adjacent horizons, mm
cmc_0_1_67_0_next - ice rain accumulated from cmc gentime for next horizon, mm
cmc_0_1_68_0 - iced graupel accumulated from cmc gentime, mm
cmc_0_1_68_0_grad - iced graupel accumulated from cmc gentime difference between adjacent horizons, mm
cmc_0_1_68_0_next - iced graupel accumulated  from cmc gentime for next horizon, mm
cmc_0_1_7_0 - instant precipitation intensivity, mm/h
cmc_0_2_2_10 - wind U component at 10m, m/s
cmc_0_2_2_1000 - wind U component at 1000 isobaric level, m/s
cmc_0_2_2_500 - wind U component at 500 isobaric level, m/s
cmc_0_2_2_700 - wind U component at 700 isobaric level, m/s
cmc_0_2_2_850 - wind U component at 850 isobaric level, m/s
cmc_0_2_2_925 - wind U component at 925 isobaric level, m/s
cmc_0_2_3_10 - wind V component at 10m, m/s
cmc_0_2_3_1000 - wind V component at 1000 isobaric level, m/s
cmc_0_2_3_500 - wind V component at 500 isobaric level, m/s
cmc_0_2_3_700 - wind V component at 700 isobaric level, m/s
cmc_0_2_3_850 - wind V component at 850 isobaric level, m/s
cmc_0_2_3_925 - wind V component at 925 isobaric level, m/s
cmc_0_3_0_0 - surface pressure, Pa
cmc_0_3_0_0_next - next horizon surface pressure, Pa
cmc_0_3_1_0 - sea level pressure, Pa
cmc_0_3_5_1000 - geopotential height at 1000 isobaric level, gpm (geopotential meter)
cmc_0_3_5_500 - geopotential height at 500 isobaric level, gpm 
cmc_0_3_5_700 - geopotential height at 700 isobaric level, gpm
cmc_0_3_5_850 - geopotential height at 850 isobaric level, gpm
cmc_0_3_5_925 - geopotential height at 925 isobaric level, gpm
cmc_0_6_1_0 - cloudiness, % from 0 to 100
cmc_available - is there any data from cmc
cmc_horizon_h - cmc horizon, h
cmc_precipitations - avg precipitations rate between adjacent horizons, mm/h
cmc_timedelta_s, difference between cmc and forecast time, s
gfs_2m_dewpoint - dew point temperature at 2m, C
gfs_2m_dewpoint_grad - dew point temperature at 2m difference between horizons, C
gfs_2m_dewpoint_next - dew point temperature on next horizon, C
gfs_a_vorticity - absolute vorticity at height 100000 Pa, s-1
gfs_available - is there any data from gfs
gfs_cloudness - sum of 3 level cloudiness, from 0 to 3
gfs_clouds_sea - Cloud mixing ratio at level 1000mb, kg/kg 0.0
gfs_horizon_h - gfs horizon, h
gfs_humidity - relative humidity at 2m, %
gfs_precipitable_water - total precipitable water, kg m^-2
gfs_precipitations - avg precipitations rate between adjacent horizons, mm/h
gfs_pressure - surface pressure, mmHg
gfs_r_velocity - vertical Velocity at 1000mb, Pa/s
gfs_soil_temperature - soil temperature at 0.0-0.1 m, C
gfs_soil_temperature_available - is there gfs soil temp data
gfs_temperature_10000 - temp at vertical level at 10000 hectopascals, C
gfs_temperature_15000 - temp at vertical level at 15000 hectopascals, C
gfs_temperature_20000 - temp at vertical level at 20000 hectopascals, C
gfs_temperature_25000 - temp at vertical level at 25000 hectopascals, C
gfs_temperature_30000 - temp at vertical level at 30000 hectopascals, C
gfs_temperature_35000 - temp at vertical level at 35000 hectopascals, C
gfs_temperature_40000 - temp at vertical level at 40000 hectopascals, C
gfs_temperature_45000 - temp at vertical level at 45000 hectopascals, C
gfs_temperature_5000 - temp at vertical level at 5000 hectopascals, C
gfs_temperature_50000 - temp at vertical level at 50000 hectopascals, C
gfs_temperature_55000 - temp at vertical level at 55000 hectopascals, C
gfs_temperature_60000 - temp at vertical level at 60000 hectopascals, C
gfs_temperature_65000 - temp at vertical level at 65000 hectopascals, C
gfs_temperature_7000 - temp at vertical level at 7000 hectopascals, C
gfs_temperature_70000 - temp at vertical level at 70000 hectopascals, C
gfs_temperature_75000 - temp at vertical level at 75000 hectopascals, C
gfs_temperature_80000 - temp at vertical level at 80000 hectopascals, C
gfs_temperature_85000 - temp at vertical level at 85000 hectopascals, C
gfs_temperature_90000 - temp at vertical level at 90000 hectopascals, C
gfs_temperature_92500 - temp at vertical level at 92500 hectopascals, C
gfs_temperature_95000 - temp at vertical level at 95000 hectopascals, C
gfs_temperature_97500 - temp at vertical level at 97500 hectopascals, C
gfs_temperature_sea - temp at 2m, C
gfs_temperature_sea_grad - temperature difference adjacent horizons at 2m
gfs_temperature_sea_interpolated - gfs_temperature_sea_interpolated between horizons, C
gfs_temperature_sea_next - next horizon temperature at 2m, C
gfs_timedelta_s - difference between gfs and forecast time, s
gfs_total_clouds_cover_high - cloud coverage (between horizons, divisible by 6) at high level, %
gfs_total_clouds_cover_low - cloud coverage (between horizons, divisible by 6) at low level, %
gfs_total_clouds_cover_low_grad - difference between low level cloud coverage on adjacent horizons, %
gfs_total_clouds_cover_low_next - next horizon cloud coverage (between horizons, divisible by 6) at low level, %
gfs_total_clouds_cover_middle - cloud coverage (between horizons, divisible by 6) at middle level, %
gfs_u_wind - 10 meter U wind component, m/s
gfs_v_wind - 10 meter V wing component, m/s
gfs_wind_speed  - wind velocity, sqrt(gfs_u_wind ** 2 + gfs_v_wind ** 2), m/s
sun_elevation - sun height proxy above horizon (without corrections for precession and diffraction)
topography_bathymetry - height above or below sea level, m
wrf_available - is there any data from wrf 1
wrf_graupel - avg graupel rate between two horizons, mm/h
wrf_hail - hail velocity on two horizons, mm/h 0.0
wrf_psfc - pressure, Pa
wrf_rain - avg rain rate between two horizons, mm/h
wrf_rh2 - humidity from 0 to 1
wrf_snow - avg snow rate between two horizons, mm/h
wrf_t2 - temperature at 2m, K
wrf_t2_grad - difference between temperatures at 2m on adjacent horizons, K
wrf_t2_interpolated - wrf_t2_interpolated between horizons, K
wrf_t2_next - next horizon temperature at 2m, K
wrf_wind_u - wind U component, m/s
wrf_wind_v - wind V component, m/s
