### ISSUE TITLE
Stuck on MT data preprocessing...

### ISSUE THREAD

**Issue by zabh0z** [yandex-research/shifts#25]
I am trying to follow instructions on 
https://github.com/yandex-research/shifts/tree/main/translation

and stuck while performing `python3 structured-uncertainty/fairseq-preprocess.py`

it seems like the repo `structured-uncertainty` doesn't contain `fairseq-preprocess.py`

**Comment by KaosEngineer** [comment]
Hey! You're right, it should be:

`python3 structured-uncertainty/preprocess.py`

**Comment by KaosEngineer** [comment]
Did this resolve your issues?
