### ISSUE TITLE
Is the framework of sdc support muti-GPU?

### ISSUE THREAD

**Issue by sty61010** [yandex-research/shifts#26]

**Comment by nband** [comment]
The baselines do not currently support multi-GPU training. However, we use a pretty standard PyTorch training loop, and it shouldn't be hard to add multi-GPU training with [Distributed Data Parallel](https://pytorch.org/tutorials/intermediate/ddp_tutorial.html).

If you do that, we would be greatly appreciative of your submitting a pull request!
