### ISSUE TITLE
download dataset, dir_metadata_cache

### ISSUE THREAD

**Issue by rttariverdi67** [yandex-research/shifts#27]
Hi,
I download dataset from [here](https://storage.yandexcloud.net/yandex-research/shifts/sdc/canonical-trn-dev-data.tar), however I cant see "train_tags.txt" and "development_tags.txt". Also I'm not quite sure that how should I set "dir_metadata_cache" in notebooks [1](https://github.com/yandex-research/shifts/blob/main/sdc/examples/analyze_dataset_metadata.ipynb) and[2](https://github.com/yandex-research/shifts/blob/main/sdc/examples/compare_rip_models.ipynb).

**Comment by gchesnokov** [comment]
Hi!
Tags files can be found inside `train.tar.gz` and `development.tar.gz` respectively.
Regarding metadata, there is a description in the readme section: https://github.com/yandex-research/shifts/tree/main/sdc#caching-dataset-metadata-for-downstream-analysis.
